# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `bin/tapioca require`.

# typed: false

require 'bootsnap/setup'
require 'bundler/setup'
require 'mkmf'
require 'rails/all'
require 'rails/test_help'
